name: build android app development

on: workflow_dispatch

jobs:
  building-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: propertilord/pl-scf-mobile
          token: ${{ secrets.GH_TOKEN }}
          ref: v1
      - name: setup keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" > propertilord.keystore.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_PASSPHRASE }}" --batch propertilord.keystore.asc > android/app/propertilord.keystore
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: install dependencies
        run: |
          yarn install
      - name: build APK
        env:
          BASE_URL: ${{secrets.BASE_URL}}
          HOST: ${{ secrets.HOST }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          STORAGE_KEY: ${{ secrets.STORAGE_KEY }}
          DESIGN_WIDTH: ${{ secrets.DESIGN_WIDTH }}
        run: |
          yarn build:apk
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pl-dev.apk
          path: android/app/build/outputs/apk/release/app-release.apk